[package]
name = "advent-of-code"
version = "0.1.0"
authors = ["Marc Carré <carre.marc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
lazy_static = "1.4.0"
regex = "1.4.2"
